### ISSUE TITLE
Add support for more sites

### ISSUE THREAD

**Issue by yashas123** [Dinokin/ComicRider#1]
Many other sites use the same reader as comicride, could you make the app flexible so that it will take any url as input and check whether the reader is supported by this ripper or not.

Example sites that use similar reader as comicride are :
comic-valkyrie.com
comic-meteor.jp
comic-polaris.jp

**Comment by Dinokin** [comment]
While the program does "ask" for comicride, its just a message. the program dont check the url to see if its from comicride or not. you can just copy the url from any of these sites and try to see if it works.

**Comment by yashas123** [comment]
Oh, it's just that when I tried some other sites it just closes without any warning, so I thought others might not be supported, so if there is no restriction on input url then I guess I can close this.
